### ISSUE TITLE
http: multiple response.WriteHeader calls

### ISSUE THREAD

**Issue by mh-cbon** [xioxu/goreq#11]
i did not check the reason, but it does not seem correct, it means you are writing twice the headers so the issued http request has invalid format.

**Comment by mh-cbon** [comment]
cf https://travis-ci.org/xioxu/goreq/jobs/398179583#L473

**Comment by xioxu** [comment]
It doesn't matter, it is the UT framework output, I just removed some useless code in UT and it is disappear.
