### ISSUE TITLE
why nullableString/Bool ?

### ISSUE THREAD

**Issue by mh-cbon** [xioxu/goreq#3]
https://github.com/xioxu/goreq/blob/f980fa68163b4df6d56f1f464561d3757e6fba2f/nullable.go#L3

would not work with (pointer to basic type) *string ? *bool ? etc

**Comment by xioxu** [comment]
@mh-cbon  Thanks for your advice and your pull request firstly.

If we use *bool, the end user have to define a variable, like:
```
followRedirect := false
goReq.Req(&goReq.ReqOptions{FollowRedirect: &followRedirect})
```
I think it is not smoothly enough, but It may more shorter than NullableBool, What do you think?

**Comment by xioxu** [comment]
I defined some help filed and method to replace the NullableType, such as goreq.TrueVal, goreq.FalseVal, gorew.NewString()
