### ISSUE TITLE
lint sugggestion

### ISSUE THREAD

**Issue by mh-cbon** [xioxu/goreq#4]
only suggesting (the link is available in the bottom links of https://godoc.org/github.com/xioxu/goreq)

https://go-lint.appspot.com/github.com/xioxu/goreq

**Comment by mh-cbon** [comment]
the doc would be happy to have an example like you posted on #nuts

**Comment by mh-cbon** [comment]
https://blog.golang.org/godoc-documenting-go-code

https://blog.golang.org/examples

**Comment by xioxu** [comment]
Good suggestion, I just added some code sample.
