### ISSUE TITLE
tag it

### ISSUE THREAD

**Issue by mh-cbon** [xioxu/goreq#6]
according to https://github.com/golang/dep/blob/master/docs/FAQ.md#how-do-i-roll-releases-that-dep-will-be-able-to-use it should be something like _x.x.x_. Add a prerelease tag if you are not totally sure the api is stable yet, such as _x.x.x-beta_. Otherwise you might also assume a breaking change api is acceptable, as long as the version does bump appropriately (major).

**Comment by xioxu** [comment]
Good advice, tks.
